# Generated by Django 4.2 on 2023-04-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tecnology',
            new_name='technology',
        ),
    ]
